Config-version: 0.1 #Don't touch it, it's just to be sure on what kind of config it is or check self-update

karma:
  ######### You can put any value you want, while they are all int and maximum_karma >= minimum-karma
  default-karma:       0
  minimum-karma: -300000
  maximum-karma:  300000

tiers:
  ######### You can add, edit or delete many tiers as you want !
  #  sampleTierName: (no spaces)
  #    tier-display-name: <string>
  #    tier-minimum-karma: <int>
  #    tier-maximum-karma: <int>
  #    commands: #set how many commands you want, without / (except for worldguards, only 1)
  #      - "command1" ### basic command
  #      - "command2 <player>" ### <player> is replaced by the player's name
  #      - "<@> command3" ### set <@> at the begin of the line makes the command sent by the console/server
  tier-3:
    tier-display-name: "&f[&4Criminal&f]&r"
    tier-minimum-karma: -300000
    tier-maximum-karma: -150000
    commands:
      - "me is the baddest."
  tier-2:
    tier-display-name: "&f[&cVillain&f]&r"
    tier-minimum-karma: -149999
    tier-maximum-karma:  -30000
    commands:
      - "me is really bad."
      - "me seriously guys."
  tier-1:
    tier-display-name: "&f[&eThug&f]&r"
    tier-minimum-karma:  -29999
    tier-maximum-karma:   -5000
    commands:
      - "me is not gentle."
  tier_0:
    tier-display-name: "&f[&7Civilian&f]&r"
    tier-minimum-karma:   -4999
    tier-maximum-karma:    4999
    commands:
      - "me is the neutral neutral alignment."
      - "help"
      - "<@>tell <player> SUP' ! must be sent by console"
  tier+1:
    tier-display-name: "&f[&aVigilante&f]&r"
    tier-minimum-karma:    5000
    tier-maximum-karma:   29999
    commands:
      - "me is now a good guy who likes Streets of Rage games serie."
      - "me is a test, it will be sent by player."
  tier+2:
    tier-display-name: "&f[&bSheriff&f]&r"
    tier-minimum-karma:   30000
    tier-maximum-karma:  149999
    commands:
      - "me has right to kill anyone who mess him, yes."
      - "me die."
  tier+3:
    tier-display-name: "&f[&6Hero&f]&r"
    tier-minimum-karma:  150000
    tier-maximum-karma:  300000
    commands:
      - "me is the hero !"
      - "me another command !"
      - "me infinite commands !"

pvp: #### THIS DOESN'T WORKS ATM
  Player:
    killer_positive-victim_positive:
      hit-karma-reward: -15
      kill-karma-reward: "<killerKarma> - ( <killerkarma> / <victimKarma> )² / 100"
    killer_positive-victim_negative:
      hit-karma-reward: 15
      kill-karma-reward: "<killerKarma> + ( <killerkarma> / <victimKarma> )² / 100"
    killer_negative-victim_positive:
      hit-karma-reward: -15
      kill-karma-reward: "<killerKarma> - ( <killerkarma> / <victimKarma> )² / 100"
    killer_negative-victim_negative:
      hit-karma-reward: 15
      kill-karma-reward: "<killerKarma> + ( <killerkarma> / <victimKarma> )² / 70"

entities:
  ######## Rou can add edit or delete any mob you want ! There is no error if you set a mob from a higher Minecraft version.
  ######## Removing a mob just set the changes to 0.
  ######## messages are compatible with 4 placeholders:
          ######## <attacker> : player who hit/kill the entity
          ######## <previousKarma> which is the karma before hit
          ######## <reward> is the hit/kill-karma-reward
          ######## <karma> is the karma after the action.
  #  MobName: # use ALT-F3 to check the name of a mob, cave sensitive. Don't use "_" between words, example : MagmaCube instead of Magma_Cube
  #    hit-karma-reward: <int> # Gives / removes specified karma when the mob is hit
  #    hit-message: <string> #Send a message to the player when the mob is hit
  #    kill-karma-reward: <int> # Gives / removes specified karma when mob is killed
  #    kill-message: <string> #send a message to the player when the mob is killed
  Bat:
    hit-karma-reward:      1
    hit-message: "Don't you fear bats ? <reward>"
    kill-karma-reward:     2
    kill-message: "<attacker>, You're the man who broke the bat ! <previousKarma> + <reward> = <karma>"
  Bee:
    hit-karma-reward:      1
    hit-message: "Run villager, RUN !!!"
    kill-karma-reward:     3
    kill-message: "<attacker> : You captured a bee ! *Animal Crossing MLG music* <previousKarma> + <reward> = <karma>"
  Blaze:
    hit-karma-reward:      5
    hit-message: "Did your torch alight ? <karma>"
    kill-karma-reward:    93
    kill-message: "No more light source... Arf."
  Cat:
    hit-karma-reward:    -10
    hit-message: "You DARE put a hand on your Master ?!!"
    kill-karma-reward:   -76
    kill-message: "WILFRIIIIIIIED !!!"
  CaveSpider:
    hit-karma-reward:      1
    hit-message: "I hate these things !"
    kill-karma-reward:   100
    kill-message: "Few..."
  Chicken:
    hit-karma-reward:     -1
    hit-message: "But... But.. BUT !!!"
    kill-karma-reward:   -10
    kill-message: "Yeah, we all prefier KFC anyway."
  Cod:
    hit-karma-reward:      1
    kill-karma-reward:     1
  Cow:
    hit-karma-reward:     -1
    kill-karma-reward:  -100
  Creeper:
    hit-karma-reward:      1
    kill-karma-reward:   100
  Dolphin:
    hit-karma-reward:     -1
    kill-karma-reward:  -100
  Donkey:
    hit-karma-reward:     -1
    kill-karma-reward:  -100
  Drowned:
    hit-karma-reward:      1
    kill-karma-reward:   100
  ElderGuardian:
    hit-karma-reward:      1
    kill-karma-reward:   100
  Enderman:
    hit-karma-reward:      1
    kill-karma-reward:   100
  Endermite:
    hit-karma-reward:      1
    kill-karma-reward:    10
  Evoker:
    hit-karma-reward:      1
    kill-karma-reward:   100
  Fox:
    hit-karma-reward:      0
    kill-karma-reward:     0
  Ghast:
    hit-karma-reward:      1
    kill-karma-reward:   100
  Guardian:
    hit-karma-reward:      1
    kill-karma-reward:   100
  Horse:
    hit-karma-reward:    -10
    kill-karma-reward:  -150
  Husk:
    hit-karma-reward:      1
    kill-karma-reward:   100
  Llama:
    hit-karma-reward:    -10
    kill-karma-reward:  -100
  MagmaCube:
    hit-karma-reward:      1
    kill-karma-reward:   100
  Mooshroom:
    hit-karma-reward:     -1
    kill-karma-reward:  -100
  Mule:
    hit-karma-reward:     -1
    kill-karma-reward:  -100
  Ocelot:
    hit-karma-reward:     -1
    kill-karma-reward:  -100
  Panda:
    hit-karma-reward:    -10
    kill-karma-reward:  1000
  Parrot:
    hit-karma-reward:    -10
    kill-karma-reward:  -100
  Phantom:
    hit-karma-reward:      1
    kill-karma-reward:   100
  Pig:
    hit-karma-reward:     -1
    kill-karma-reward:  -100
  PolarBear:
    hit-karma-reward:    -10
    kill-karma-reward:  -100
  Pufferfish:
    hit-karma-reward:      0
    kill-karma-reward:     0
  Rabbit:
    hit-karma-reward:    -10
    kill-karma-reward:  -100
  Ravager:
    hit-karma-reward:      1
    kill-karma-reward:   100
  Salmon:
    hit-karma-reward:      0
    kill-karma-reward:     0
  Sheep:
    hit-karma-reward:    -10
    kill-karma-reward:  -100
  Shulker:
    hit-karma-reward:      1
    kill-karma-reward:   100
  Silverfish:
    hit-karma-reward:      1
    kill-karma-reward:   100
  Skeleton:
    hit-karma-reward:      1
    kill-karma-reward:   100
  SkeletonHorse:
    hit-karma-reward:      1
    kill-karma-reward:   100
  Slime:
    hit-karma-reward:      1
    kill-karma-reward:   100
  Spider:
    hit-karma-reward:      1
    kill-karma-reward:   100
  Squid:
    hit-karma-reward:      0
    kill-karma-reward:     0
  Stray:
    hit-karma-reward:      1
    kill-karma-reward:   100
  TraderLlama:
    hit-karma-reward:    -10
    kill-karma-reward: -1000
  TropicalFish:
    hit-karma-reward:      0
    kill-karma-reward:     0
  Turtle:
    hit-karma-reward:     -5
    kill-karma-reward:   200
  vex:
    hit-karma-reward:      1
    kill-karma-reward:   100
  Villager:
    hit-karma-reward:   -100
    kill-karma-reward: -1000
  Vindicator:
    hit-karma-reward:      1
    kill-karma-reward:   100
  WanderingTrader:
    hit-karma-reward:    -70
    kill-karma-reward:  -700
  WitherSkeleton:
    hit-karma-reward:      1
    kill-karma-reward:   100
  Wolf:
    hit-karma-reward:      3
    kill-karma-reward:    30
  Zombie:
    hit-karma-reward:      5
    hit-message: "Aim their head !"
    kill-karma-reward:    58
    kill-message: "Burn the corpse."
  ZombiePigman:
    hit-karma-reward:      0
    kill-karma-reward:     0
  ZombieVillager:
    hit-karma-reward:      0
    kill-karma-reward:  -100