Config-version: 0.1 #Don't touch it, it's just to be sure on what kind of config it is or check self-update

karma:
  ######### You can put any value you want, while they are all int and maximum_karma >= minimum-karma
  default-karma:       0
  minimum-karma: -300000
  maximum-karma:  300000

tiers:
  ######### You can add, edit or delete many tiers as you want !
  #  sampleTierName: (no spaces)
  #    tier-display-name: <string>
  #    tier-minimum-karma: <int>
  #    tier-maximum-karma: <int>
  #    commands: #set how many commands you want, without / (except for worldguards, only 1)
  #      - "command1" ### basic command
  #      - "command2 <player>" ### <player> is replaced by the player's name
  #      - "<@> command3" ### set <@> at the begin of the line makes the command sent by the console/server
  tier-3:
    tier-display-name: "&f[&4Criminal&f]&r"
    tier-minimum-karma: -300000
    tier-maximum-karma: -150000
    commands:
      - "me is the baddest."
  tier-2:
    tier-display-name: "&f[&cVillain&f]&r"
    tier-minimum-karma: -149999
    tier-maximum-karma:  -30000
    commands:
      - "me is really bad."
      - "me seriously guys."
  tier-1:
    tier-display-name: "&f[&eThug&f]&r"
    tier-minimum-karma:  -29999
    tier-maximum-karma:   -5000
    commands:
      - "me is not gentle."
  tier_0:
    tier-display-name: "&f[&7Civilian&f]&r"
    tier-minimum-karma:   -4999
    tier-maximum-karma:    4999
    commands:
      - "me is the neutral neutral alignment."
      - "help"
      - "<@>tell <player> SUP' ! must be sent by console"
  tier+1:
    tier-display-name: "&f[&aVigilante&f]&r"
    tier-minimum-karma:    5000
    tier-maximum-karma:   29999
    commands:
      - "me is now a good guy who likes Streets of Rage games serie."
      - "me is a test, it will be sent by player."
  tier+2:
    tier-display-name: "&f[&bSheriff&f]&r"
    tier-minimum-karma:   30000
    tier-maximum-karma:  149999
    commands:
      - "me has right to kill anyone who mess him, yes."
      - "me die."
  tier+3:
    tier-display-name: "&f[&6Hero&f]&r"
    tier-minimum-karma:  150000
    tier-maximum-karma:  300000
    commands:
      - "me is the hero !"
      - "me another command !"
      - "me infinite commands !"