mysql:
  active: false
  host: "localhost"
  port: 3306
  database: "database_name"
  username: "root"
  password: ""

general:
  lang: "en_EN"
  decimal-number-to-show: 2
  delay-between-hit-messages: 5
  delay-between-kill-messages: 10
  use-worldguard: false #works only for Worldguard 7+
  use-action-bar-for-actions: true

karma:
  default-karma:       0
  minimum-karma: -300000
  maximum-karma:  300000

tiers:
  tier-3:
    tier-display-name: "&f[&4Criminal&f]&r"
    tier-minimum-karma: -300000
    tier-maximum-karma: -150000
    commands:
      - "me &8is the baddest <TIER>."
      - "me another command"
      - "<@>me command from console"
  tier-2:
    tier-display-name: "&f[&cVillain&f]&r"
    tier-minimum-karma: -149999
    tier-maximum-karma:  -30000
    commands:
      - "me &cis really bad."
      - "me &cseriously guys."
    commands-on-up:
      - "me I'm not the most wanted anymore... Better !"
    commands-on-down:
      - "me I've made a big raberry today, ahah !"
  tier-1:
    tier-display-name: "&f[&eThug&f]&r"
    tier-minimum-karma:  -29999
    tier-maximum-karma:   -5000
    commands:
      - "me &eis not gentle."
    commands-on-up:
      - "me But I'm better than some guys !"
    commands-on-down:
      - "me But this wasn't me !"
  tier_0:
    tier-display-name: "&f[&7Civilian&f]&r"
    tier-minimum-karma:   -4999
    tier-maximum-karma:    4999
    commands:
      - "me &7is the neutral neutral alignment."
      - "<@>me &6<PLAYER> &aHey ! Your karma is &6<KARMA> &r!"
    commands-on-up:
      - "me I'm not a thug anymore !"
    commands-on-down:
      - "me I've made some mistakes, back to normal."
  tier+1:
    tier-display-name: "&f[&aVigilante&f]&r"
    tier-minimum-karma:    5000
    tier-maximum-karma:   29999
    commands:
      - "me &ais now a good guy who likes Streets of Rage games serie."
      - "me &ais a test, it will be sent by player."
      - "<@>me must not be sent by player but by console."
    commands-on-up:
      - "me I'm a good guy !"
    commands-on-down:
      - "me I just loss my sheriff star..."
  tier+2:
    tier-display-name: "&f[&bSheriff&f]&r"
    tier-minimum-karma:   30000
    tier-maximum-karma:  149999
    commands:
      - "me &bhas right to kill anyone who mess him, yes."
    commands-on-up:
      - "me I AM THE LAW ! DROP YOU WEAPONS !"
    commands-on-down:
      - "me Heroes ? Nah."
  tier+3:
    tier-display-name: "&f[&6Hero&f]&r"
    tier-minimum-karma:  150000
    tier-maximum-karma:  300000
    commands:
      - "me &6is the hero !"
      - "me &6another command !"
      - "<@>me You can create an infinite amount of commands and tiers !"

times:
  use-both-system-and-worlds-time: "NONE" #can be replaced by WORLDS, SYSTEM and BOTH or NONE
  #NONE Doesn't check time
  #WORLDS Check only the worlds-time
  #SYSTEM Check only the server/system time
  #BOTH check WORLDS AND SYSTEM. both must be TRUE.
  worlds-times: #use the time where the attacker / killer is You can add all the time-X you want with custom name
    time-1:
      starting-time: "09:00"
      ending-time: "20:00"
      chance: 100
    time-2:
      starting-time: "20:00"
      ending-time: "22:00"
      chance: 66
    time-3:
      starting-time: "22:00"
      ending-time: "01:00"
      chance: 30
  system-times: #use the server real life time. You can add all the time-X you want, with custom name
    time-1:
      starting-time: "08:00"
      ending-time: "12:00"
      chance: 100
    time-2:
      starting-time: "13:00"
      ending-time: "21:00"
      chance: 30

pvp:
  # The 2nd argument must be <VICTIM_KARMA> OR a number, inside brackets.
  hit-reward-variables: #FORMULA IS     attackerKarma + [1] * ([2] + [3]) / [4]
    1: -1
    2: "<VICTIM_KARMA>"
    3: 3000
    4: 50
  kill-reward-variables: #FORMULA IS     attackerKarma + [1] * ([2] + [3]) / [4]
    1: -1
    2: "<VICTIM_KARMA>"
    3: 3000
    4: 10
  crime-time: #if a player attacks another one, everybody can attack him back without karma changes (unless if the defender is an agressor)
    enable: false
    delay: 300 #delay in second that a player is an agressor.
    # Enable or not the karma change if the defender won/less some karma or stay at the same karma.
    # Useful for avoid messages in a future update too.
    active-on-up: true
    active-on-still: false
    active-on-down: false
  #Sends a message to <attacker> when hitting / killing another player. You can use <attacker>, <attackerKarma>, <victim> and <victimKarma>.
  hit-message-on-karma-increase: "&aThat scum will not escape from that !"
  kill-message-on-karma-increase: "&bThat bastard is now finished !"
  hit-message-on-karma-decrease: "&cYou attack a honnest people !"
  kill-message-on-karma-decrease: "&cSonovabitch !"

entities:
  Bee:
    hit-karma-reward:      1
    hit-message: "Run villager, RUN !!!"
    kill-karma-reward:     3
    kill-message: "<ATTACKER> : You captured a bee ! &5*Animal Crossing MLG music* &a<OLD_KARMA> + <VALUE> = <KARMA>"
  Cat:
    hit-karma-reward:    -10
    hit-message: "&cYou DARE put a hand on your Master ?!!"
    kill-karma-reward:   -76
    kill-message: "&4&lWILFRIIIIIIIED !!!"
  EnderDragon:
    hit-karma-reward:      1
    hit-message: "&aKEEP GOING"
    kill-karma-reward: 10000
    kill-message: "&6&lYou did it ! You finally did it !"
  Skeleton:
    hit-karma-reward:      1
    kill-karma-reward:   100
  SkeletonHorse:
    hit-karma-reward:      1
    kill-karma-reward:   100
  TraderLlama:
    hit-karma-reward:    -11
    kill-karma-reward:  -356
  Villager:
    hit-karma-reward:    -34
    kill-karma-reward:  -651
  Wolf:
    hit-message: "Hunt a wolf doesn't change your karma : &d<KARMA>"
    kill-message: "You successfully hunt the wolf : &5<KARMA>"
  Zombie:
    hit-karma-reward:      5
    hit-message: "Aim his head !"
    kill-karma-reward:    58
    kill-message: "Burn the corpse."
  ZombieVillager:
    hit-karma-reward:      0
    kill-karma-reward:  -100