name: Karma
version: 1.4.0
description: Make your players actions have consequences !
api-version: 1.15
author: Rosstail
website: https://www.spigotmc.org/resources/karma.76077
softdepend:
  - WorldGuard
main: fr.rosstail.karma.Karma
commands:
  karma:
    description: Check your own karma (player)
    usage: /karma
    permission: karma.own
    permission-message: You don't have permission !
  karma <player>:
    description: Check another player karma
    usage: /karma <player>
    permission: karma.other
    permission-message: You don't have permission !
  karma set [player] [amount]:
    description: Directly set the karma of a player
    usage: /karma set [player] [amount]
    permission: karma.set
    permission-message: You don't have permission !
  karma add [player] [amount]:
    description: Add specified amount of a player karma
    usage: /karma add [player] [amount]
    permission: karma.add
    permission-message: You don't have permission !
  karma remove [player] [amount]:
    description: Remove specified amount of a player karma
    usage: /karma remove [player] [amount]
    permission: karma.remove
    permission-message: You don't have permission !
  karma reset [player]:
    description: Set player's karma to default
    usage: /karma [player] reset
    permission: karma.reset
    permission-message: You don't have permission !
  karma reload:
    description: Reloads the plugin configuration
    usage: /karma reload
    permission: karma.reload
    permission-message: You don't have permission !
permissions:
  karma.own:
    default: true
  karma.other:
    default: false
  karma.set:
    default: op
  karma.add:
    default: op
  karma.remove:
    default: op
  karma.reset:
    default: op
  karmaa.reload:
    default: op
  karma.*:
    default: op
    description: Gives all karma plugin permissions
    children:
      karma.own: true
      karma.other: true
      karma.set: true
      karma.add: true
      karma.remove: true
      karma.reset: true