name: Karma
version: 1.0
main: fr.rosstail.karma.Karma
commands:
  karma:
    description: Check your own karma (player)
    usage: /karma
    permission: karma.karma.own
    permission-message: You don't have permission !
  karma <player>:
    description: Check another player karma (permission needed)
    usage: /karma <player>
    permission: karma.karma.other
    permission-message: You don't have permission !
  karma set [player] [amount]:
    description: Directly set the karma of a player (permission needed)
    usage: /karma set [player] [amount]
    permission: karma.set.other
    permission-message: You don't have permission !
  karma add [player] [amount]:
    description: Directly set the karma of a player, negative value decrease karma (permission needed)
    usage: /karma add [player] [amount]
    permission: karma.add.other
    permission-message: You don't have permission !
  karma remove [player] [amount]:
    description: Directly set the karma of a player, negative value increase karma (permission needed)
    usage: /karma remove [player] [amount]
    permission: karma.remove.other
    permission-message: You don't have permission !
  karma reset [player]:
    description: Set player's karma to default one (permission needed)
    usage: /karma [player] reset
    permission: karma.reset.other
    permission-message: You don't have permission !