name: Karma
version: 1.0
main: fr.rosstail.karma.Karma
commands:
  karma:
    description: Check your own karma (Player)
    usage: /karma
    permission: karma.karma.own
    permission-message: You don't have permission !
  karma <player>:
    description: Check another player karma
    usage: /karma <player>
    permission: karma.karma.other
    permission-message: You don't have permission !
  karma set:
    description: Directly set the karma of a player
    usage: /karma [player] set [amount]
    permission: karma.set.other
    permission-message: You don't have permission !